services:
  # northstar:
  #   build: .
  #   ports:
  #     - "${NORTHSTAR_DNS_PORT:-8053}:${NORTHSTAR_DNS_PORT:-8053}/udp"
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   env_file: .env
  #   environment:
  #     - TZ=Europe/Berlin
  #     - NORTHSTAR_MODE=${NORTHSTAR_MODE:-prod}
  #     - NORTHSTAR_CACHE_ADDR=valkey:6379
  #   depends_on:
  #     - valkey
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2"
  #         memory: 2048M

  northstar-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${NORTHSTAR_DNS_PORT:-8053}:${NORTHSTAR_DNS_PORT:-8053}/udp"
      - "${NORTHSTAR_METRICS_PORT:-9153}:${NORTHSTAR_METRICS_PORT:-9153}"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - .:/app
    env_file: .env
    environment:
      - TZ=Europe/Berlin
      - NORTHSTAR_TZ=Europe/Berlin
      - NORTHSTAR_MODE=dev
      - NORTHSTAR_CACHE_ADDR=valkey:6379
    depends_on:
      - valkey
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 512M

  valkey:
    image: valkey/valkey:alpine
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 2G

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    restart: unless-stopped
