services:
  northstar:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "9053:53"
      - "9053:53/udp"
      - "9153:9153"
    cap_add:
      - NET_BIND_SERVICE
    env_file: prod.env
    # depends_on:
    #   - valkey
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  northstar-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8053:53"
      - "8053:53/udp"
      - "8153:9153"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - .:/app
    env_file: dev.env
    # depends_on:
    #   - valkey

  # valkey:
  #   image: valkey/valkey:alpine
  #   restart: unless-stopped
  #
  # redisinsight:
  #   image: redis/redisinsight:latest
  #   ports:
  #     - "5540:5540"
  #   restart: unless-stopped
